name: JIT Access CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List project files
        run: ls

      - name: Say Hello
        run: echo "GitHub Actions is working!"